name: cli
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  path: ^1.6.0
  args: ^1.5.2
  qr: ^1.2.0
  pdf: ^1.5.0
  dio: ^3.0.9
  tuple: ^1.0.3
  image: ^2.1.12

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0